#!/usr/bin/env bash
#
# Automated installer/bootstrapper for inconnect-agent on Ubuntu hosts.
# The script installs dependencies, fetches the source code, builds the binary,
# configures systemd, prepares SQLite + Xray directories, and starts the service.

set -euo pipefail

log() {
  echo "[+] $*"
}

require_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    echo "This script must be run as root." >&2
    exit 1
  fi
}

require_root

# Tunable parameters (override via environment variables before running the script)
# Repository URL must be overridden to point at the actual Git remote.
REPO_URL="${REPO_URL:-https://example.com/inconnect-agent.git}"
BRANCH="${BRANCH:-main}"
INSTALL_DIR="${INSTALL_DIR:-/opt/inconnect-agent}"
BIN_PATH="${BIN_PATH:-/usr/local/bin/inconnect-agent}"
SERVICE_NAME="${SERVICE_NAME:-inconnect-agent}"
SERVICE_USER="${SERVICE_USER:-inconnect}"
SERVICE_GROUP="${SERVICE_GROUP:-inconnect}"
SERVICE_ENV="${SERVICE_ENV:-/etc/default/inconnect-agent}"
DB_PATH="${DB_PATH:-/var/lib/inconnect-agent/ports.db}"
CONFIG_DIR="${CONFIG_DIR:-/etc/xray}"
LISTEN_ADDR="${LISTEN_ADDR:-127.0.0.1:8080}"
PUBLIC_IP="${PUBLIC_IP:-}"
AUTH_TOKEN="${AUTH_TOKEN:-}"
MIN_PORT="${MIN_PORT:-50001}"
MAX_PORT="${MAX_PORT:-50250}"
DOCKER_IMAGE="${DOCKER_IMAGE:-teddysun/xray:latest}"
DOCKER_BINARY="${DOCKER_BINARY:-/usr/bin/docker}"
CONTAINER_NAME="${CONTAINER_NAME:-xray-ss2022}"
API_PORT="${API_PORT:-10085}"
METHOD="${METHOD:-2022-blake3-aes-128-gcm}"
SHARD_COUNT="${SHARD_COUNT:-1}"
SHARD_SIZE="${SHARD_SIZE:-0}"
SHARD_PORT_STEP="${SHARD_PORT_STEP:-1}"
SHARD_PREFIX="${SHARD_PREFIX:-xray-ss2022}"
SHARDS="${SHARDS:-}"
RESTART_INTERVAL="${RESTART_INTERVAL:-0}"

apt_install() {
  log "Installing OS dependencies..."
  apt-get update -y
  DEBIAN_FRONTEND=noninteractive apt-get install -y \
    git golang-go docker.io curl rsync
}

setup_user() {
  if ! getent group "$SERVICE_GROUP" >/dev/null 2>&1; then
    log "Creating service group $SERVICE_GROUP..."
    groupadd --system "$SERVICE_GROUP"
  fi
  if ! id -u "$SERVICE_USER" >/dev/null 2>&1; then
    log "Creating service user $SERVICE_USER..."
    useradd --system --create-home --shell /usr/sbin/nologin \
      --gid "$SERVICE_GROUP" "$SERVICE_USER"
  fi
  usermod -aG docker "$SERVICE_USER" || true
}

LOCAL_SOURCE_DIR="${LOCAL_SOURCE_DIR:-}"

fetch_repo() {
  if [[ -n "$LOCAL_SOURCE_DIR" ]]; then
    if [[ ! -d "$LOCAL_SOURCE_DIR" ]]; then
      echo "LOCAL_SOURCE_DIR '$LOCAL_SOURCE_DIR' does not exist" >&2
      exit 1
    fi
    log "Copying source from ${LOCAL_SOURCE_DIR}..."
    rm -rf "$INSTALL_DIR"
    install -d -m 0755 "$INSTALL_DIR"
    rsync -a --exclude '.git' "${LOCAL_SOURCE_DIR}/" "${INSTALL_DIR}/"
    return
  fi
  if [[ -d "$INSTALL_DIR/.git" ]]; then
    log "Updating repository in $INSTALL_DIR..."
    git -C "$INSTALL_DIR" fetch origin
    git -C "$INSTALL_DIR" checkout "$BRANCH"
    git -C "$INSTALL_DIR" pull --ff-only origin "$BRANCH"
  else
    if [[ "$REPO_URL" == "https://example.com/inconnect-agent.git" ]]; then
      echo "ERROR: REPO_URL is still the placeholder. Set REPO_URL or LOCAL_SOURCE_DIR." >&2
      exit 1
    fi
    log "Cloning repository..."
    rm -rf "$INSTALL_DIR"
    install -d -m 0755 "$(dirname "$INSTALL_DIR")"
    git clone --branch "$BRANCH" "$REPO_URL" "$INSTALL_DIR"
  fi
}

build_binary() {
  log "Building agent binary..."
  (cd "$INSTALL_DIR" && go build -o "$BIN_PATH" ./cmd/inconnect-agent)
  chown "$SERVICE_USER":"$SERVICE_GROUP" "$BIN_PATH"
  chmod 0755 "$BIN_PATH"
}

prepare_dirs() {
  log "Preparing directories..."
  install -d -m 0755 "$(dirname "$DB_PATH")" "$CONFIG_DIR"
  chown -R "$SERVICE_USER":"$SERVICE_GROUP" "$(dirname "$DB_PATH")" "$CONFIG_DIR"
}

write_env_file() {
  log "Writing environment file $SERVICE_ENV..."
  cat >"$SERVICE_ENV" <<EOF
# Auto-generated by scripts/install.sh
INCONNECT_FLAGS="-listen=${LISTEN_ADDR} \
-db-path=${DB_PATH} \
-config-dir=${CONFIG_DIR} \
-public-ip=${PUBLIC_IP} \
-auth-token=${AUTH_TOKEN} \
-min-port=${MIN_PORT} \
-max-port=${MAX_PORT} \
-docker-image=${DOCKER_IMAGE} \
-docker-binary=${DOCKER_BINARY} \
-container-name=${CONTAINER_NAME} \
-api-port=${API_PORT} \
-method=${METHOD} \
-shard-count=${SHARD_COUNT} \
-shard-size=${SHARD_SIZE} \
-shard-port-step=${SHARD_PORT_STEP} \
-shard-prefix=${SHARD_PREFIX} \
-restart-interval=${RESTART_INTERVAL}"
EOF
  if [[ -n "$SHARDS" ]]; then
    echo 'INCONNECT_FLAGS="$INCONNECT_FLAGS -shards='"${SHARDS}"'"' >>"$SERVICE_ENV"
  fi
  chmod 0644 "$SERVICE_ENV"
}

write_service_unit() {
  log "Creating systemd unit..."
  cat >/etc/systemd/system/${SERVICE_NAME}.service <<EOF
[Unit]
Description=Inconnect Agent for Xray Shadowsocks
After=network-online.target docker.service
Requires=docker.service

[Service]
User=${SERVICE_USER}
Group=${SERVICE_GROUP}
EnvironmentFile=${SERVICE_ENV}
ExecStart=${BIN_PATH} \$INCONNECT_FLAGS
Restart=always
RestartSec=3
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
EOF
}

enable_services() {
  systemctl enable --now docker
  log "Pulling docker image ${DOCKER_IMAGE}..."
  ${DOCKER_BINARY} pull "${DOCKER_IMAGE}"
  systemctl daemon-reload
  systemctl enable --now "${SERVICE_NAME}.service"
  systemctl status --no-pager "${SERVICE_NAME}.service"
}

main() {
  apt_install
  if [[ -z "$PUBLIC_IP" ]]; then
    PUBLIC_IP="$(curl -fsSL https://api.ipify.org || true)"
  fi
  setup_user
  fetch_repo
  build_binary
  prepare_dirs
  write_env_file
  write_service_unit
  enable_services
  log "Installation complete. API is available at ${LISTEN_ADDR}."
}

main "$@"
