#!/usr/bin/env bash
#
# Automated installer/bootstrapper for inconnect-agent on Ubuntu hosts.
# The script installs dependencies, fetches the source code, builds the binary,
# configures systemd, prepares SQLite + sing-box directories, and starts the service.

set -euo pipefail

log() {
  echo "[+] $*"
}

require_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    echo "This script must be run as root." >&2
    exit 1
  fi
}

require_root

# Tunable parameters (override via environment variables before running the script)
BIN_PATH="${BIN_PATH:-/usr/local/bin/inconnect-agent}"
SERVICE_NAME="${SERVICE_NAME:-inconnect-agent}"
SERVICE_USER="${SERVICE_USER:-inconnect}"
SERVICE_GROUP="${SERVICE_GROUP:-inconnect}"
SERVICE_ENV="${SERVICE_ENV:-/etc/default/inconnect-agent}"
DB_PATH="${DB_PATH:-/var/lib/inconnect-agent/ports.db}"
CONFIG_DIR="${CONFIG_DIR:-/etc/singbox}"
DOCKER_IMAGE="${DOCKER_IMAGE:-ghcr.io/sagernet/sing-box}"
DOCKER_BINARY="${DOCKER_BINARY:-/usr/bin/docker}"
BIN_SOURCE="${BIN_SOURCE:-./inconnect-agent}"
CONFIG_SOURCE="${CONFIG_SOURCE:-./config.yaml}"
CONFIG_FILE="${CONFIG_FILE:-/etc/inconnect-agent/config.yaml}"
AUTH_TOKEN="${AUTH_TOKEN:-}"
PUBLIC_IP="${PUBLIC_IP:-}"
LISTEN_ADDR="${LISTEN_ADDR:-}"

apt_install() {
  log "Installing OS dependencies..."
  apt-get update -y
  DEBIAN_FRONTEND=noninteractive apt-get install -y \
    docker.io curl gettext-base
}

setup_user() {
  if ! getent group "$SERVICE_GROUP" >/dev/null 2>&1; then
    log "Creating service group $SERVICE_GROUP..."
    groupadd --system "$SERVICE_GROUP"
  fi
  if ! id -u "$SERVICE_USER" >/dev/null 2>&1; then
    log "Creating service user $SERVICE_USER..."
    useradd --system --create-home --shell /usr/sbin/nologin \
      --gid "$SERVICE_GROUP" "$SERVICE_USER"
  fi
  usermod -aG docker "$SERVICE_USER" || true
}

prepare_dirs() {
  log "Preparing directories..."
  install -d -m 0755 "$(dirname "$DB_PATH")" "$CONFIG_DIR"
  chown -R "$SERVICE_USER":"$SERVICE_GROUP" "$(dirname "$DB_PATH")" "$CONFIG_DIR"
}

detect_public_ip() {
  if [[ -n "$PUBLIC_IP" ]]; then
    return
  fi
  if PUBLIC_IP=$(ip route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if ($i=="src") {print $(i+1); exit}}'); then
    if [[ -n "$PUBLIC_IP" ]]; then
      return
    fi
  fi
  PUBLIC_IP=$(curl -fsSL https://api.ipify.org || true)
}

install_binary() {
  if [[ ! -f "$BIN_SOURCE" ]]; then
    echo "Binary not found at $BIN_SOURCE" >&2
    exit 1
  fi
  log "Installing binary to $BIN_PATH..."
  install -m 0755 "$BIN_SOURCE" "$BIN_PATH"
  chown "$SERVICE_USER":"$SERVICE_GROUP" "$BIN_PATH"
}

render_config_file() {
  if [[ ! -f "$CONFIG_SOURCE" ]]; then
    echo "Config template not found at $CONFIG_SOURCE" >&2
    exit 1
  fi
  detect_public_ip
  export PUBLIC_IP AUTH_TOKEN LISTEN_ADDR DB_PATH CONFIG_DIR DOCKER_IMAGE DOCKER_BINARY
  log "Rendering config file $CONFIG_FILE from $CONFIG_SOURCE..."
  install -d -m 0755 "$(dirname "$CONFIG_FILE")"
  envsubst <"$CONFIG_SOURCE" >"$CONFIG_FILE"
  chown "$SERVICE_USER":"$SERVICE_GROUP" "$CONFIG_FILE"
  chmod 0640 "$CONFIG_FILE"
}

write_env_file() {
  log "Writing environment file $SERVICE_ENV..."
  cat >"$SERVICE_ENV" <<EOF
# Auto-generated by scripts/install.sh
INCONNECT_FLAGS="-config=${CONFIG_FILE}"
EOF
  chmod 0644 "$SERVICE_ENV"
}

write_service_unit() {
  log "Creating systemd unit..."
  cat >/etc/systemd/system/${SERVICE_NAME}.service <<EOF
[Unit]
Description=Inconnect Agent for Xray Shadowsocks
After=network-online.target docker.service
Requires=docker.service

[Service]
User=${SERVICE_USER}
Group=${SERVICE_GROUP}
EnvironmentFile=${SERVICE_ENV}
ExecStart=${BIN_PATH} \$INCONNECT_FLAGS
Restart=always
RestartSec=3
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
EOF
}

enable_services() {
  systemctl enable --now docker
  log "Pulling docker image ${DOCKER_IMAGE}..."
  ${DOCKER_BINARY} pull "${DOCKER_IMAGE}"
  systemctl daemon-reload
  systemctl enable --now "${SERVICE_NAME}.service"
  systemctl status --no-pager "${SERVICE_NAME}.service"
}

main() {
  apt_install
  setup_user
  install_binary
  prepare_dirs
  render_config_file
  write_env_file
  write_service_unit
  enable_services
  log "Installation complete. Config: ${CONFIG_FILE}."
}

main "$@"
